export const tarotCards = [
	"Joker",
	"Büyücü",
	"Azize",
	"İmparatoriçe",
	"İmparator",
	"Aziz",
	"Aşıklar",
	"Araba",
	"Adalet",
	"Ermiş",
	"Kader Çarkı",
	"Güç",
	"Asılan Adam",
	"Ölüm",
	"Denge",
	"Şeytan",
	"Kule",
	"Yıldız",
	"Ay",
	"Güneş",
	"Mahkeme",
	"Dünya",
	"Değnek Kralı",
	"Değnek Kraliçesi",
	"Değnek Şövalyesi",
	"Değnek Prensi",
	"Değnek Onlusu",
	"Değnek Dokuzlusu",
	"Değnek Sekizlisi",
	"Değnek Yedilisi",
	"Değnek Altılısı",
	"Değnek Beşlisi",
	"Değnek Dörtlüsü",
	"Değnek Üçlüsü",
	"Değnek İkilisi",
	"Değnek Ası",
	"Kupaların Ası",
	"Kupa İkilisi",
	"Kupa Üçlüsü",
	"Kupa Dörtlüsü",
	"Kupa Beşlisi",
	"Kupa Altılısı",
	"Kupa Yedilisi",
	"Kupa Sekizlisi",
	"Kupa Dokuzlusu",
	"Kupa Onlusu",
	"Kupa Prensi",
	"Kupa Şövalyesi",
	"Kupa Kraliçesi",
	"Kupa Kralı",
	"Kılıçların Ası",
	"Kılıç İkilisi",
	"Kılıç Üçlüsü",
	"Kılıç Dörtlüsü",
	"Kılıç Beşlisi",
	"Kılıç Altılısı",
	"Kılıç Yedilisi",
	"Kılıç Sekizlisi",
	"Kılıç Dokuzlusu",
	"Kılıç Onlusu",
	"Kılıçların Prensi",
	"Kılıçların Şövalyesi",
	"Kılıçların Kraliçesi",
	"Kılıçların Kralı",
	"Tılsımların Ası",
	"Tılsım İkilisi",
	"Tılsım Üçlüsü",
	"Tılsım Dörtlüsü",
	"Tılsım Beşlisi",
	"Tılsım Altılısı",
	"Tılsım Yedilisi",
	"Tılsım Sekizlisi",
	"Tılsım Dokuzlusu",
	"Tılsım Onlusu",
	"Tılsımların Prensi",
	"Tılsımların Şövalyesi",
	"Tılsımların Kraliçesi",
	"Tılsımların Kralı",
]
